# Generated by Django 3.0.8 on 2020-07-31 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='agreed_swap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_agreed_swap', to='products.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='pending_offers',
            field=models.ManyToManyField(related_name='products_pending_offers', to='products.Product'),
        ),
    ]
