# Generated by Django 3.0.8 on 2020-07-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200731_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rejected_offers',
            field=models.ManyToManyField(related_name='products_rejected_offers', to='products.Product'),
        ),
    ]
