# Generated by Django 3.0.8 on 2020-08-17 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_rejected_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_owned_by_current_user',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_offers',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='agreed_swap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_agreed_swap', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pending_offers',
            field=models.ManyToManyField(blank=True, related_name='products_pending_offers', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rejected_offers',
            field=models.ManyToManyField(blank=True, related_name='products_rejected_offers', to='products.Product'),
        ),
    ]
